### PR TITLE
Collect arrow

### PR DESCRIPTION
**Pull request by anthony-khong**
Hi @behrica, just some cosmetic changes for now, but I think there are a couple more things to do:

1. Get to 100% test coverage. Doesn't have to be now, but we need to check the ifs in `typed-action`.
2. Make sure that other parts of the repo have the right provided dependencies.

This is a very cool PR. Thank you so much for working on it!

### CODE REVIEW

**Comment by behrica** [comment]
> Hi @behrica, just some cosmetic changes for now, but I think there are a couple more things to do:
> 
> 1. Get to 100% test coverage. Doesn't have to be now, but we need to check the ifs in `typed-action`.

I saw the coverage report, and it is very strange that it marks some lines in typed-action as "non covered".

I am pretty sure, that they are all covered, because I did them test-first.
Is there something special in the coverage tool, because of the  nested "case" statement ?

**Comment by behrica** [comment]
> > Hi @behrica, just some cosmetic changes for now, but I think there are a couple more things to do:
> > 
> > 1. Get to 100% test coverage. Doesn't have to be now, but we need to check the ifs in `typed-action`.
> 
> I saw the coverage report, and it is very strange that it marks some lines in typed-action as "non covered".
> 
> I am pretty sure, that they are all covered, because I did them test-first.
> Is there something special in the coverage tool, because of the nested "case" statement ?

Maybe I hit this issue with cloverage ?
https://github.com/cloverage/cloverage/issues/82

**Comment by anthony-khong** [comment]
Aha, yes, I should clarify. You have indeed tested them all, but cloverage can be quite anal. It's honestly not a big deal, I think we can merge without the 100% test coverage.

However, if you're curious here's the partially missed lines highlighted in yellow:

Screenshot 2020-11-04 at 16 57 23

I believe what it's saying is that we haven't tested the then branch of the `:get` actions. So we need to put in some nils in our examples to check that indeed they get parsed to `nil`. And given that we missed one case in the `case`, the entire `case` is only partially covered too.

**Comment by behrica** [comment]
> I believe what it's saying is that we haven't tested the then branch of the `:get` actions. So we need to put in some nils in our examples to check that indeed they get parsed to `nil`. And given that we missed one case in the `case`, the entire `case` is only partially covered too.

Yes, I will generate one file parquet file with all types and NA values

**Comment by anthony-khong** [comment]
Hi @behrica, I've merged with your latest commit. Do you have any comments about the changes I've made here? 

If you have no objections (most of them are cosmetics + some stuff for CI purposes), would you like to merge this PR, then I'll merge the one from upstream?

**Comment by behrica** [comment]
I just integrated your changes localy ...

**Comment by behrica** [comment]
I will just push it know.

**Comment by behrica** [comment]
@anthony-khong 
I merged your latest changes in. You can merge from upstream

**Pull request merged**
